name: lym_nutrition
description: Application de nutrition intelligente avec IA

# La version suit le format majeur.mineur.patch+numéro
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture & État
  flutter_bloc: ^9.1.1
  provider: ^6.0.5
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  
  # Persistance des données
  shared_preferences: ^2.5.3
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  
  # Réseau
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.4.1
  
  # UI/UX
  google_fonts: ^5.1.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  font_awesome_flutter: ^10.4.0
  flutter_dotenv: ^5.1.0
  
  # Speech Recognition & AI
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  
  # Internationalisation
  intl: ^0.18.1
  
  # Utilitaires
  json_annotation: ^4.8.1
  collection: ^1.17.1
  logger: ^2.0.1
  percent_indicator: ^4.2.5
  material_design_icons_flutter: ^7.0.7296
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9

  uuid: any
  crypto: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Génération de code
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
  # Analyse de code
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/animations/